# Generated by Django 5.1.5 on 2025-02-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="message",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="chat",
            name="response",
            field=models.TextField(),
        ),
    ]
